name = "Christmasville 1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4caa1fc41cdbc44bccdf64b43f9e32e76496ac73fc175e97a5fb895bec754754"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
